insert into falla values (10,'Set 0687 Activity Booklet 1');
insert into falla values (11,'Baseplate 16 x 30 with Set 080 Yellow House Print');
insert into falla values (12,'Baseplate 16 x 24 with Set 080 Red House Print');
insert into falla values (13,'Homemaker Bookcase 2 x 4 x 4');
insert into falla values (14,'Baseplate 24 x 32');
insert into falla values (15,'Sticker Sheet #1 for 41055-1');
insert into falla values (16,'Sticker for Set 10019 - (43274/4170393)');
insert into falla values (17,'Sticker for Set 10026 - (44942/4184185)');
insert into falla values (18,'Sticker for Set 10029 - (4216816)');
insert into falla values (19,'Sticker for Set 10036 - (821407)');
insert into falla values (20,'Pullback Motor 8 x 4 x 2/3');
insert into falla values (21,'Minifig Hair Tousled');
insert into falla values (22,'Minifig Sword [Uruk-hai]');
insert into falla values (23,'Minifig Beard, Rounded End [Gandalf]');
insert into falla values (24,'Minifig Sword Small');
insert into falla values (25,'Minifig Hair Long Straight with Elf Ears [Plain]');
insert into falla values (26,'Body / Head Gollum');
insert into falla values (27,'Body / Head Gollum - Wide Eyes');
insert into falla values (28,'Body / Head Gollum - Narrow Eyes');
insert into falla values (29,'Arm, Bent [Gollum]');
insert into falla values (30,'Arm Goblin King, Left');
insert into falla values (31,'Hand Cave Troll, Left');
insert into falla values (32,'Arm Goblin King, Right');
insert into falla values (33,'Hand Cave Troll, Right');
insert into falla values (34,'Minifig Beard - Full with Braided Moustache Ends');
insert into falla values (35,'Minifig Hair Orc [Plain]');
insert into falla values (36,'Minifig Hair Orc with Dark Tan Ears Print');
insert into falla values (37,'Minifig Hair Orc with Olive Green Ears Print');
insert into falla values (38,'ADULT FIGURE W/HEADSET');
insert into falla values (39,'ADULT FIGURE W/HEADSET (Yellow) NO. 6');
insert into falla values (40,'MASK, BATMAN, NO. 1 with Bat Print');
insert into falla values (41,'Mask Batman with Crack Print');
insert into falla values (42,'Arm Giant, Right');
insert into falla values (43,'Arm Giant, Right with Blue Darkseid Print');
insert into falla values (44,'Hand Hulk - Right');
insert into falla values (45,'Hand Hulk - Left');
insert into falla values (46,'Hulk Body [Plain]');
insert into falla values (47,'Hulk Body with Dark Tan Pants Print');
insert into falla values (48,'Hulk Body with Dark Purple Pants Print');
insert into falla values (49,'Sticker for Set 10129 - (48074/4214068)');
insert into falla values (50,'Sticker for Set 10134 - (48981/4221407)');
insert into falla values (51,'Sticker for Set 10144 - (53390/4269558)');
insert into falla values (52,'Arm Giant, Left');
insert into falla values (53,'Arm Giant, Left with Blue Darkseid Print');
insert into falla values (54,'Sticker for Set 10159 - (4264102)');
insert into falla values (55,'Minifig Cap, Santa [Plain]');
insert into falla values (56,'Minifig Santa Hat with Red Top Print');
insert into falla values (57,'Minifig Bag with Handle');
insert into falla values (58,'Pretzel');
insert into falla values (59,'Minifig Trophy Cup Small');
insert into falla values (60,'Minifig Head Cover - Ghost Shroud with Open Mouth');
insert into falla values (61,'RIGHT MINI FIGURE ROBOT LEG');
insert into falla values (62,'Rock 1 x 2 Crystal Stepped');
insert into falla values (63,'Rock Stepped with Dark Green Swamp Gas Print');
insert into falla values (64,'MOONSTONE NO 1');
insert into falla values (65,'Rock Stepped with Black Bat Print');
insert into falla values (66,'Rock Stepped with Black Zombie Print');
insert into falla values (67,'Rock Stepped with White Lightning Print');
insert into falla values (68,'Minifig Wings Fairy');
insert into falla values (69,'Minifig Bladed Claw, Spread');
insert into falla values (70,'Sticker for Set 10187 - (63292/4528621)');
insert into falla values (71,'Sticker for Set 10188 - (64169/453341)');
insert into falla values (72,'Minifig Flipper [Thick]');
insert into falla values (73,'Sticker for Set 10192 - (10192/4528138)');
insert into falla values (74,'ADULT FIG. NO. 1 2012 V2');
insert into falla values (75,'Plate 4 X 8');
insert into falla values (76,'Bracket 1 x 2 - 1 x 4 [Rounded Corners]');
insert into falla values (77,'Tile 6 x 6 with Bottom Tubes');
insert into falla values (78,'Sticker for Set 10212 - (88529/4568123)');
insert into falla values (79,'Sticker for Set 10216 - (90051/4582442)');
insert into falla values (80,'Cardboard Game Board - Life of George');
insert into falla values (81,'Sticker for Set 10219');
insert into falla values (82,'Sticker for Set 10220 - Sheet 1 (94347/4614415)');
insert into falla values (83,'Sticker for Set 10220 - Sheet 2 (94349/4614425)');
insert into falla values (84,'Round Sign with 30 Speed Limit Print');
insert into falla values (85,'Sticker for Set 10232 - (12949 / 6022692)');
insert into falla values (86,'Sticker for Set 10233 - (12953/6022720)');
insert into falla values (87,'Sticker for Set 10235');
insert into falla values (88,'10240stk01');
insert into falla values (89,'10240stk02');
insert into falla values (90,'10240stk03');
insert into falla values (91,'Minifig Compound Bow &amp');
insert into falla values (92,'Pirate Comic - The Golden Medallion');
insert into falla values (93,'Minifig Hair with Bat Ears [Plain]');
insert into falla values (94,'Minifig Head Modified Werewolf [Plain]');
insert into falla values (95,'Minifig Head Modified Werewolf');
insert into falla values (96,'Arm with Wing');
insert into falla values (97,'Coffin 2 x 4 x 6 Lid [Plain]');
insert into falla values (98,'Minifig Helmet with Front Prongs [Plain]');
insert into falla values (99,'t 1030 Activity Booklet 10 - Wheels');
insert into falla values (100,'Set 1030 Activity Booklet 11 - Conveyors');
insert into falla values (101,'Set 1030 Activity Booklet 12 - Advanced Gearing');
insert into falla values (102,'Set 1030 Activity Booklet 13 - Pistons');
insert into falla values (103,'Set 1030 Activity Booklet 14 - Merry-go-round');
insert into falla values (104,'Set 1030 Activity Booklet 15 - Cranes');
insert into falla values (105,'Set 1030 Activity Booklet 17 - Water Wheels');
insert into falla values (106,'Set 1030 Activity Booklet 18 - Windmills');
insert into falla values (107,'Set 1030 Activity Booklet 19 - Simple Steering');
insert into falla values (108,'Set 1030 Activity Booklet 2 - Levers');
insert into falla values (109,'Set 1030 Activity Booklet 20 - Advanced Steering');
insert into falla values (110,'Set 1030 Activity Booklet 3 - Supports');
insert into falla values (111,'Set 1030 Activity Booklet 4 - Lifting &amp');
insert into falla values (112,'Set 1030 Activity Booklet 5 - Pulleys &amp');
insert into falla values (113,'Set 1030 Activity Booklet 6 - Gears');
insert into falla values (114,'Set 1030 Activity Booklet 7 - More Gears');
insert into falla values (115,'Set 1030 Activity Booklet 8 - Angles');
insert into falla values (116,'Set 1030 Activity Booklet 9 - Flywheels');
insert into falla values (117,'Set 1032 Activity Booklet 10 - Appliances');
insert into falla values (118,'Set 1032 Activity Booklet 11 - Right Angle Drives');
insert into falla values (119,'Set 1032 Activity Booklet 12 - Clamps');
insert into falla values (120,'Set 1032 Activity Booklet 13 - Mixers &amp');
insert into falla values (121,'Set 1032 Activity Booklet 14 - Valves &amp');
insert into falla values (122,'Set 1032 Activity Booklet 15 - Gearing Down');
insert into falla values (123,'Set 1032 Activity Booklet 16 - Differentials');
insert into falla values (124,'Set 1032 Activity Booklet 17 - Cranes');
insert into falla values (125,'Set 1032 Activity Booklet 18 - Conveyors');
insert into falla values (126,'Set 1032 Activity Booklet 19 - Drawbridges &amp');
insert into falla values (127,'Set 1032 Activity Booklet 2 - Bracing &amp');
insert into falla values (128,'Set 1032 Activity Booklet 20 - Robots');
insert into falla values (129,'Set 1032 Activity Booklet 4 - Wheels &amp');
insert into falla values (130,'Set 1032 Activity Booklet 5 - Saws');
insert into falla values (131,'Set 1032 Activity Booklet 6 - Small Machinery');
insert into falla values (132,'Set 1032 Activity Booklet 7 - Chains');
insert into falla values (133,'Set 1032 Activity Booklet 8 - Chain Drives');
insert into falla values (134,'Set 1032 Activity Booklet 9 - Winches');
insert into falla values (135,'Arm Cave Troll - Left with Scales Print');
insert into falla values (136,'Arm Cave Troll - Right with Scales Print');
insert into falla values (137,'Antenna 6H without Stud Hole');
insert into falla values (138,'Horse, Moveable Legs [Plain]');
insert into falla values (139,'Horse, Moveable Legs with Gray Bridle Print');
insert into falla values (140,'Horse, Moveable Legs with Dark Brown Bridle Print');
insert into falla values (141,'Sticker Sheet for 9498-1');
insert into falla values (142,'Minifig Cape Cloth, Narrow with Single Top Hole');
insert into falla values (143,'LID FOR FRAME 2X4X2');
insert into falla values (144,'Sticker Sheet for 9473-1');
insert into falla values (145,'Sticker for Set 9474 - (10636/6005725)');
insert into falla values (146,'Sticker for Set 10226');
insert into falla values (147,'Sticker Sheet for 9499-1');
insert into falla values (148,'Torso Bat with Vestigial Minifig Arms');
insert into falla values (149,'Minifig Pauldron with Pre Vizsla Print');
insert into falla values (150,'Road Sign Cantilever Curved with "SHELL" Print');
insert into falla values (151,'Road Sign Cantilever Curved with "POLICE" Print');
insert into falla values (152,'Minifig Skirt Cloth with Diamond Points');
insert into falla values (153,'Duplo Turntable 2 x 2');
insert into falla values (154,'Technic Shock Absorber 9.5L, Piston Rod');
insert into falla values (155,'Minifig Cape Cloth, Ringwraith Style Tattered');
insert into falla values (156,'Minifig Visor Top Hinge [Plain]');
insert into falla values (157,'VISOR NR. 1 NO. 11');
insert into falla values (158,'VISOR NR, 1 NO. 12');
insert into falla values (159,'Minifig Helmet with Large Curved Flexible Horns');
insert into falla values (160,'Set 1090 Activity Booklet A - Ferris Wheel');
insert into falla values (161,'Set 1090 Activity Booklet D - Conveyer Belt');
insert into falla values (162,'Set 1090 Activity Booklet E - Robot Arm');
insert into falla values (163,'Electric Cable USB for Mindstorms EV3 (2 meter)');
insert into falla values (164,'Technic Gear 8 Tooth [Reinforced]');
insert into falla values (165,'Set 1092 Activity Booklet A - Plotter');
insert into falla values (166,'Set 1092 Activity Booklet E - Crane');
insert into falla values (167,'Lego Computer Interface A User"s Guide (12059)');
insert into falla values (168,'Baseplate 24 x 32 with Squared Corners');
insert into falla values (169,'Baseplate 24 x 32 with Rounded Corners');
insert into falla values (170,'Baseplate 24 x 32 with Dots Print [363 / 555]');
insert into falla values (171,'Baseplate 24 x 32 with Dots Print [354 / 560-2]');
insert into falla values (172,'Baseplate 24 x 32 with Dots Print [358]');
insert into falla values (173,'Baseplate 24 x 32 with Dots Print [345]');
insert into falla values (174,'Baseplate 24 x 32 with Dots Print [545-2 / 351]');
insert into falla values (175,'Baseplate 24 x 32 with Dots Print [149]');
insert into falla values (176,'Baseplate 24 x 32 with Dots Print [346-2]');
insert into falla values (177,'Baseplate 24 x 32 with Dots Print [353]');
insert into falla values (178,'Baseplate 24 x 32 with Dots Print [1601]');
insert into falla values (179,'Baseplate 24 x 32 with Dots Prints [361]');
insert into falla values (180,'Minifig Ring 1 x 1');
insert into falla values (181,'Flag 2 x 2 Square [Thick Clips]');
insert into falla values (182,'Flag 2 x 2 with AT-ST Print [4486 / 9679]');
insert into falla values (183,'FLAG WITH 2 HOLDERS &quot');
insert into falla values (184,'FLAG W/ 2 HOLDERS Classic Space Print');
insert into falla values (185,'Lamp Post 2 x 2 x 7 with 4 Base Flutes');
insert into falla values (186,'Barb Large Flexible [Claw, Horn]');
insert into falla values (187,'Bar Holder with Clip');
insert into falla values (188,'Wing 9L with Stylized Feathers');
insert into falla values (189,'Gorilla Fist');
insert into falla values (190,'Minifig Axe Head - Twin Bladed');
insert into falla values (191,'Minifig Feathered Wing');
insert into falla values (192,'Minifig Hammer Head');
insert into falla values (193,'Minifig Sword Serrated with Bar Holder');
insert into falla values (194,'Fly Wheel Fairing Lion Shape');
insert into falla values (195,'Fly Wheel Fairing Bird Shape');
insert into falla values (196,'Fly Wheel Fairing Crocodile Shape');
insert into falla values (197,'Fly Wheel Fairing Wolf Shape');
insert into falla values (198,'Fly Wheel Fairing Gorilla Shape');
insert into falla values (199,'Rip Cord Flexible with Handle');
insert into falla values (200,'Rock 1 x 1 Crystal 4 Point');
insert into falla values (201,'Minifig Mask Chima Lion [Plain]');
insert into falla values (202,'Duplo, Brick 2 x 4 x 2 Arch');
insert into falla values (203,'Electric Mindstorms EV3 Cable 25 cm');
insert into falla values (204,'Minifig Sword - Elven Warrior');
insert into falla values (205,'Hero Factory Brain');
insert into falla values (206,'Hero Factory Brain with Red Centre');
insert into falla values (207,'Duplo Brick 2 x 2 x 1 1/2 with Curve');
insert into falla values (208,'Brick 2 x 2 x 1 1/2 - Curved Top');
insert into falla values (209,'Minifig Snowshoe [Short Front End]');
insert into falla values (210,'Arch 2 x 4 x 2');
insert into falla values (211,'Tile Special 2 x 2 Inverted');
insert into falla values (212,'FLAT TILE 2X2 INV with keypad print');
insert into falla values (213,'FLAT TILE 2X2, INV., NO.15');
insert into falla values (214,'Tyre 21 x 9.9');
insert into falla values (215,'Brick Special 1 x 2 with Studs on 1 Side');
insert into falla values (216,'Plate 3 x 3');
insert into falla values (217,'Plate, Round 6 x 6 with Hole');
insert into falla values (218,'Bracket 5 x 2 x 1 1/3');
insert into falla values (219,'Door 1 x 12 x 16 Castle Gate (Portcullis)');
insert into falla values (220,'Minifig Helmet SW Clone Trooper [Plain]');
insert into falla values (221,'Minifig Helmet - Republic Trooper [Plain]');
insert into falla values (222,'Minifig Mask Wolf');
insert into falla values (223,'Minifig Mask Wolf with Fangs and Gray Nose Print');
insert into falla values (224,'Horse Foal [Plain]');
insert into falla values (225,'Friends Accessories School Bag');
insert into falla values (226,'Minifig Judge"s Gavel');
insert into falla values (227,'Minifig Oval Tray');
insert into falla values (228,'Minifig Roller Skate');
insert into falla values (229,'Minifig Hair Long with Curls (Judge"s Peruke)');
insert into falla values (230,'Minifig Hair - Short, Wavy with Side Part');
insert into falla values (231,'Minifig Mask Cyclops with Horn [Plain]');
insert into falla values (232,'Minifig Cap, Worker');
insert into falla values (233,'Minifig Hat, Police with Badge [Plain]');
insert into falla values (234,'HAT, NO. 33 Police');
insert into falla values (235,'MINI MECH ARMOR NO.3');
insert into falla values (236,'Minifig Hair - Long with Braided Front');
insert into falla values (237,'Minifig Mask Chicken [Plain]');
insert into falla values (238,'MINI CHICKEN WING');
insert into falla values (239,'Mini Mech Helmet [Plain]');
insert into falla values (240,'MINI MECH HELMET NO.3');
insert into falla values (241,'Friends Slide Curved');
insert into falla values (242,'Hero Factory Armour with Rock Spikes');
insert into falla values (243,'Hero Factory Helmet Visor with Clip');
insert into falla values (244,'Hero Factory Head with Handle');
insert into falla values (245,'Hero Factory Full Torso Armour with 4 Handles');
insert into falla values (246,'Technic Axle Connector 2 x 3 Quadruple');
insert into falla values (247,'Hero Factory Shield with Half "H"');
insert into falla values (248,'Hero Factory Mask (Evo 2013)');
insert into falla values (249,'Hero Factory Mask (Rocka 2013)');
insert into falla values (250,'Hero Factory Mask [Surge]');
insert into falla values (251,'Hero Factory Mask (Stormer 2013)');
insert into falla values (252,'Hero Factory Mask (Bulk 2013)');
insert into falla values (253,'Hero Factory Mask (Furno 2013)');
insert into falla values (254,'Hero Factory Mask (Breez 2013)');
insert into falla values (255,'Hero Factory Mask (Ogrum)');
insert into falla values (256,'Hero Factory Mask (Scarox)');
insert into falla values (257,'Hero Factory Mask (Pyrox)');
insert into falla values (258,'Hero Factory Mask (Dragon Bolt)');
insert into falla values (259,'Windscreen 4 x 4 x 4 2/3 with Handle');
insert into falla values (260,'Slope Curved 2 x 8 x 2 Double');
insert into falla values (261,'Wedge 3 x 4 x 2/3 Cutout');
insert into falla values (262,'Aircraft Fuselage Curved Forward 6 x 8 Top');
insert into falla values (263,'Hero Factory Mask (Aquagon) ');
insert into falla values (264,'Aircraft Fuselage Curved Forward 6 x 8 Bottom');
insert into falla values (265,'Hero Factory Mask (Bruizer)');
insert into falla values (266,'Hero Factory Mask [Frost Beast]');
insert into falla values (267,'Ladder 16 x 3.5 with Side Supports');
insert into falla values (268,'Slope, Curved 2 x 8 x 2 Inverted Double');
insert into falla values (269,'Hero Factory Weapon - Blade with Curved Tip');
insert into falla values (270,'Large Figure Visor - Vladek');
insert into falla values (271,'Rancor Paw with Pin');
insert into falla values (272,'Rancor Claw');
insert into falla values (273,'Hero Factory Armour with Spikes');
insert into falla values (274,'Duplo Building Wall 1 x 8 x 6 with Window Opening');
insert into falla values (275,'Hero Factory Weapon - Axe/Sword Double Spiked');
insert into falla values (276,'Hero Factory Weapon - Axe/Sword with Jagged Blade');
insert into falla values (277,'Rancor Body with Black Eyes Print');
insert into falla values (278,'Rancor Arm Right with Dark Bluish Gray Ring Print');
insert into falla values (279,'Rancor Arm Left');
insert into falla values (280,'Duplo, Brick 2 x 3 x 2 with Curved Top');
insert into falla values (281,'Duplo Building Door Frame 4 x 4 x 3');
insert into falla values (282,'Duplo Goat - Single Back Stud');
insert into falla values (283,'Duplo Goat');
insert into falla values (284,'Duplo Teddy Bear');
insert into falla values (285,'Duplo Teddy Bear');
insert into falla values (286,'Minifig Tools');
insert into falla values (287,'Friends Hips and Shorts [41171]');
