insert into localidad values (1,'Zárate');
insert into localidad values (2,'Villa Ocampo');
insert into localidad values (3,'Villa Lugano');
insert into localidad values (4,'Villaguay');
insert into localidad values (5,'Villa Gesell');
insert into localidad values (6,'Tigre');
insert into localidad values (7,'Tandil');
insert into localidad values (8,'San Vicente');
insert into localidad values (9,'Santo Tomé');
insert into localidad values (10,'Santa Elena');
insert into localidad values (11,'San Pedro');
insert into localidad values (12,'San Luis del Palmar');
insert into localidad values (13,'San Lorenzo');
insert into localidad values (14,'San Javier');
insert into localidad values (15,'San Isidro');
insert into localidad values (16,'Saladas');
insert into localidad values (17,'Retiro');
insert into localidad values (18,'Resistencia');
insert into localidad values (19,'Reconquista');
insert into localidad values (20,'Quilmes');
insert into localidad values (21,'Puerto Rico');
insert into localidad values (22,'Puerto Iguazú');
insert into localidad values (23,'Puerto Esperanza');
insert into localidad values (24,'Puerto Eldorado');
insert into localidad values (25,'Posadas');
insert into localidad values (26,'Pontevedra');
insert into localidad values (27,'Pirané');
insert into localidad values (28,'Paso de los Libres');
insert into localidad values (29,'Oberá');
insert into localidad values (30,'Necochea');
insert into localidad values (31,'Morón');
insert into localidad values (32,'Monte Caseros');
insert into localidad values (33,'Montecarlo');
insert into localidad values (34,'Mercedes');
insert into localidad values (35,'Mercedes');
insert into localidad values (36,'Mar del Plata');
insert into localidad values (37,'Luján');
insert into localidad values (38,'La Plata');
insert into localidad values (39,'La Paz');
insert into localidad values (40,'Jardín América');
insert into localidad values (41,'Gualeguaychú');
insert into localidad values (42,'Gualeguay');
insert into localidad values (43,'Goya');
insert into localidad values (44,'Gobernador Ingeniero Valentín Virasoro');
insert into localidad values (45,'General José de San Martín');
insert into localidad values (46,'Garupá');
insert into localidad values (47,'Formosa');
insert into localidad values (48,'Fontana');
insert into localidad values (49,'Federal');
insert into localidad values (50,'Esquina');
insert into localidad values (51,'El Soberbio');
insert into localidad values (52,'Dolores');
insert into localidad values (53,'Curuzú Cuatiá');
insert into localidad values (54,'Corrientes');
insert into localidad values (55,'Concordia');
insert into localidad values (56,'Concepción del Uruguay');
insert into localidad values (57,'Colegiales');
insert into localidad values (58,'Chajarí');
insert into localidad values (59,'Campana');
insert into localidad values (60,'Buenos Aires');
insert into localidad values (61,'Barranqueras');
insert into localidad values (62,'Azul');
insert into localidad values (63,'Avellaneda');
insert into localidad values (64,'Aristóbulo del Valle');
insert into localidad values (65,'Zapala');
insert into localidad values (66,'Yerba Buena');
insert into localidad values (67,'Villa Regina');
insert into localidad values (68,'Villa Paula de Sarmiento');
insert into localidad values (69,'Villa Nueva');
insert into localidad values (70,'Villa María');
insert into localidad values (71,'Villa Dolores');
insert into localidad values (72,'Villa Constitución');
insert into localidad values (73,'Villa Carlos Paz');
insert into localidad values (74,'Villa Ángela');
insert into localidad values (75,'Villa Allende');
insert into localidad values (76,'Viedma');
insert into localidad values (77,'Victoria');
insert into localidad values (78,'Vera');
insert into localidad values (79,'Venado Tuerto');
insert into localidad values (80,'Veinticinco de Mayo');
insert into localidad values (81,'Ushuaia');
insert into localidad values (82,'Unquillo');
insert into localidad values (83,'Tres Isletas');
insert into localidad values (84,'Tres Arroyos');
insert into localidad values (85,'Trelew');
insert into localidad values (86,'Termas de Río Hondo');
insert into localidad values (87,'Tartagal');
insert into localidad values (88,'Tafí Viejo');
insert into localidad values (89,'Sunchales');
insert into localidad values (90,'Santo Tomé');
insert into localidad values (91,'Santiago del Estero');
insert into localidad values (92,'Santa Rosa');
insert into localidad values (93,'Santa Lucía');
insert into localidad values (94,'Santa Fe de la Vera Cruz');
insert into localidad values (95,'San Salvador de Jujuy');
insert into localidad values (96,'San Ramón de la Nueva Orán');
insert into localidad values (97,'San Rafael');
insert into localidad values (98,'San Pedro');
insert into localidad values (99,'San Nicolás de los Arroyos');
insert into localidad values (100,'San Miguel de Tucumán');
insert into localidad values (101,'San Martín de los Andes');
insert into localidad values (102,'San Martín');
insert into localidad values (103,'San Luis');
insert into localidad values (104,'San Justo');
insert into localidad values (105,'San Juan');
insert into localidad values (106,'San José de Jáchal');
insert into localidad values (107,'San Jorge');
insert into localidad values (108,'San Francisco');
insert into localidad values (109,'San Fernando del Valle de Catamarca');
insert into localidad values (110,'San Antonio Oeste');
insert into localidad values (111,'Salta');
insert into localidad values (112,'Rufino');
insert into localidad values (113,'Rosario');
insert into localidad values (114,'Río Tercero');
insert into localidad values (115,'Río Segundo');
insert into localidad values (116,'Río Gallegos');
insert into localidad values (117,'Río Cuarto');
insert into localidad values (118,'Río Ceballos');
insert into localidad values (119,'Rawson');
insert into localidad values (120,'Rafaela');
insert into localidad values (121,'Quitilipi');
insert into localidad values (122,'Punta Alta');
insert into localidad values (123,'Puerto Madryn');
insert into localidad values (124,'Presidencia Roque Sáenz Peña');
insert into localidad values (125,'Pocito');
insert into localidad values (126,'Plottier');
insert into localidad values (127,'Pergamino');
insert into localidad values (128,'Pérez');
insert into localidad values (129,'Paraná');
insert into localidad values (130,'Palpalá');
insert into localidad values (131,'Olavarría');
insert into localidad values (132,'Nueve de Julio');
insert into localidad values (133,'Neuquén');
insert into localidad values (134,'Morteros');
insert into localidad values (135,'Monteros');
insert into localidad values (136,'Mendoza');
insert into localidad values (137,'Marcos Juárez');
insert into localidad values (138,'Machagai');
insert into localidad values (139,'Lincoln');
insert into localidad values (140,'Libertador General San Martín');
insert into localidad values (141,'Las Breñas');
insert into localidad values (142,'La Rioja');
insert into localidad values (143,'La Falda');
insert into localidad values (144,'La Calera');
insert into localidad values (145,'Laboulaye');
insert into localidad values (146,'Junín');
insert into localidad values (147,'Joaquín V. González');
insert into localidad values (148,'Jesús María');
insert into localidad values (149,'Granadero Baigorria');
insert into localidad values (150,'Gobernador Gálvez');
insert into localidad values (151,'General Roca');
insert into localidad values (152,'General Pinedo');
insert into localidad values (153,'General Pico');
insert into localidad values (154,'General Enrique Mosconi');
insert into localidad values (155,'Gálvez');
insert into localidad values (156,'Firmat');
insert into localidad values (157,'Famaillá');
insert into localidad values (158,'Esquel');
insert into localidad values (159,'Esperanza');
insert into localidad values (160,'Embarcación');
insert into localidad values (161,'Embalse');
insert into localidad values (162,'El Bolsón');
insert into localidad values (163,'Diamante');
insert into localidad values (164,'Deán Funes');
insert into localidad values (165,'Cutral-Có');
insert into localidad values (166,'Cruz del Eje');
insert into localidad values (167,'Crespo');
insert into localidad values (168,'Cosquín');
insert into localidad values (169,'Coronel Suárez');
insert into localidad values (170,'Coronda');
insert into localidad values (171,'Córdoba');
insert into localidad values (172,'Comodoro Rivadavia');
insert into localidad values (173,'Cipolletti');
insert into localidad values (174,'Cinco Saltos');
insert into localidad values (175,'Chivilcoy');
insert into localidad values (176,'Chimbas');
insert into localidad values (177,'Chilecito');
insert into localidad values (178,'Charata');
insert into localidad values (179,'Chacabuco');
insert into localidad values (180,'Centenario');
insert into localidad values (181,'Caucete');
insert into localidad values (182,'Catriel');
insert into localidad values (183,'Castelli');
insert into localidad values (184,'Casilda');
insert into localidad values (185,'Carcarañá');
insert into localidad values (186,'Capitán Bermúdez');
insert into localidad values (187,'Cañada de Gómez');
insert into localidad values (188,'Caleta Olivia');
insert into localidad values (189,'Bell Ville');
insert into localidad values (190,'Bella Vista');
insert into localidad values (191,'Bahía Blanca');
insert into localidad values (192,'Arroyo Seco');
insert into localidad values (193,'Arroyito');
insert into localidad values (194,'Añatuya');
insert into localidad values (195,'Alta Gracia');
insert into localidad values (196,'Allen');
insert into localidad values (197,'Alderetes');
insert into localidad values (198,'Albardón');
insert into localidad values (199,'Aguilares');
insert into localidad values (200,'Villa Santa Rita');
insert into localidad values (201,'Villa Mercedes');
insert into localidad values (202,'San Carlos de Bariloche');
insert into localidad values (203,'Adrogué');
